
################################################################
## WARNING: DO NOT UPDATE CARGO.TOML DIRECTLY SINCE IT IS OVERWRITTEN DURING BUILD
##   ONLY UPDATE CARGO_TEMPLATE.TOML
################################################################

[package]
name = "my_chess_ql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[profile.dev]
#opt-level = 3
#debug = 0

[lib]
name = "my_chess_ql"
crate-type = ["cdylib"]

[dependencies]
#array2d = "0.2.1"
simple-error = "0.2.3"
json = "0.12.4"
lazy_static = "1.4.0"
regex = "0.2"
rand = "0.8.4"
pyo3 = "0.15.1"
unroll = "0.1.5"
arrayvec = "0.7.2"
clap = "2.34.0"
float-cmp = "0.9.0"
itertools = "0.10.3"
tensorflow = "0.16.1"
#tensorflow = { version = "0.16.1", default-features = false }
#bitintr = "0.3.0"
#rayon = "1.5.1"
#core_simd = { git = "https://github.com/rust-lang/portable-simd" }

#[dependencies.pyo3]
#version = "0.15.1"
#features = ["extension-module"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]